# Generated by Django 4.1.7 on 2023-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_alter_chat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='chat_messages', to='Messaging.message'),
        ),
    ]
