# Generated by Django 4.1 on 2023-01-20 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Management', '0002_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 5, 25, 299924)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_the_week',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=10),
        ),
    ]
